# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ElectricGoKartConstraints.xdc

# Block Designs: bd/ElectricGoKart/ElectricGoKart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart || ORIG_REF_NAME==ElectricGoKart} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_processing_system7_0_0/ElectricGoKart_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_processing_system7_0_0 || ORIG_REF_NAME==ElectricGoKart_processing_system7_0_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_xadc_wiz_0_0/ElectricGoKart_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_xadc_wiz_0_0 || ORIG_REF_NAME==ElectricGoKart_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_ps7_0_axi_periph_0/ElectricGoKart_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_ps7_0_axi_periph_0 || ORIG_REF_NAME==ElectricGoKart_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_rst_ps7_0_100M_0/ElectricGoKart_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_rst_ps7_0_100M_0 || ORIG_REF_NAME==ElectricGoKart_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_xbar_0/ElectricGoKart_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_xbar_0 || ORIG_REF_NAME==ElectricGoKart_xbar_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_axi_gpio_0_0/ElectricGoKart_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_axi_gpio_0_0 || ORIG_REF_NAME==ElectricGoKart_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_axi_gpio_1_0/ElectricGoKart_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_axi_gpio_1_0 || ORIG_REF_NAME==ElectricGoKart_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_axi_gpio_2_0/ElectricGoKart_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_axi_gpio_2_0 || ORIG_REF_NAME==ElectricGoKart_axi_gpio_2_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_axi_gpio_3_0/ElectricGoKart_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_axi_gpio_3_0 || ORIG_REF_NAME==ElectricGoKart_axi_gpio_3_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_axi_gpio_4_0/ElectricGoKart_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_axi_gpio_4_0 || ORIG_REF_NAME==ElectricGoKart_axi_gpio_4_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_Encoder_Driver_0_0/ElectricGoKart_Encoder_Driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_Encoder_Driver_0_0 || ORIG_REF_NAME==ElectricGoKart_Encoder_Driver_0_0} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_PWM_Generator_0_1/ElectricGoKart_PWM_Generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_PWM_Generator_0_1 || ORIG_REF_NAME==ElectricGoKart_PWM_Generator_0_1} -quiet] -quiet

# IP: bd/ElectricGoKart/ip/ElectricGoKart_auto_pc_0/ElectricGoKart_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ElectricGoKart_auto_pc_0 || ORIG_REF_NAME==ElectricGoKart_auto_pc_0} -quiet] -quiet

# XDC: bd/ElectricGoKart/ElectricGoKart_ooc.xdc
